services:
  - type: web
    name: micromarin-oauth-partner-ui
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ClientCredentials__Authority
        sync: false
      - key: ClientCredentials__ClientId
        sync: false
      - key: ClientCredentials__ClientSecret
        sync: false
      - key: ClientCredentials__PostLogoutRedirectUri
        sync: false
